/**
 * `ascendops bot create <agent_name>` — interactive Telegram bot provisioning.
 *
 * Walks the customer through:
 *   1. Creating the bot at @BotFather (or pasting a token they already have)
 *   2. Verifying the BOT_TOKEN via getMe
 *   3. Sending /start to the bot from their own Telegram account
 *   4. Capturing CHAT_ID + ALLOWED_USER via getUpdates
 *   5. Writing agents/<name>/.env (chmod 600) with the three values, merging
 *      with whatever existing .env keys are present so other secrets stay put.
 *
 * Errors are owned in conversation, not hallucinated past — each failing step
 * prints what went wrong, what the customer can do about it, and exits non-zero
 * without leaving partial state on disk.
 */
import { Command } from 'commander';
import { createInterface, type Interface } from 'readline';
import { existsSync, readdirSync, readFileSync, writeFileSync, chmodSync } from 'fs';
import { join } from 'path';
import { TelegramAPI, formatValidateError } from '../telegram/api.js';

function rl(): Interface {
  return createInterface({ input: process.stdin, output: process.stdout });
}

function ask(iface: Interface, question: string): Promise<string> {
  return new Promise(resolve => iface.question(question, answer => resolve(answer.trim())));
}

function askRequired(iface: Interface, question: string, errorMsg: string): Promise<string> {
  return new Promise(async resolve => {
    while (true) {
      const answer = await ask(iface, question);
      if (answer) {
        resolve(answer);
        return;
      }
      console.log(`  ${errorMsg}`);
    }
  });
}

function findProjectRoot(): string {
  const candidates = [
    process.env.CORTEXTOS_DIR,
    process.env.CTX_FRAMEWORK_ROOT,
    process.env.CTX_PROJECT_ROOT,
    process.cwd(),
  ].filter(Boolean) as string[];
  for (const c of candidates) {
    if (existsSync(join(c, 'orgs'))) return c;
  }
  return process.cwd();
}

function resolveAgentDir(projectRoot: string, agentName: string, org?: string): { dir: string; org: string } | null {
  const orgsDir = join(projectRoot, 'orgs');
  if (!existsSync(orgsDir)) return null;

  if (org) {
    const dir = join(orgsDir, org, 'agents', agentName);
    return existsSync(dir) ? { dir, org } : null;
  }

  const orgs = readdirSync(orgsDir, { withFileTypes: true })
    .filter(d => d.isDirectory())
    .map(d => d.name);
  const matches = orgs.filter(o => existsSync(join(orgsDir, o, 'agents', agentName)));
  if (matches.length === 1) {
    return { dir: join(orgsDir, matches[0], 'agents', agentName), org: matches[0] };
  }
  if (matches.length > 1) {
    console.error(`  Agent "${agentName}" exists under multiple orgs: ${matches.join(', ')}. Pass --org <name> to disambiguate.`);
    return null;
  }
  return null;
}

function parseExistingEnv(envPath: string): Record<string, string> {
  if (!existsSync(envPath)) return {};
  const lines = readFileSync(envPath, 'utf-8').split('\n');
  const out: Record<string, string> = {};
  for (const line of lines) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;
    const eq = trimmed.indexOf('=');
    if (eq <= 0) continue;
    out[trimmed.slice(0, eq).trim()] = trimmed.slice(eq + 1);
  }
  return out;
}

function writeEnv(envPath: string, values: Record<string, string>, originalContent: string | null): void {
  // Preserve original comments + non-key lines if we have a previous file; only
  // replace lines for keys we are setting. Otherwise write a minimal header.
  const setKeys = new Set(Object.keys(values));
  let output: string[] = [];

  if (originalContent !== null) {
    const seenKeys = new Set<string>();
    for (const line of originalContent.split('\n')) {
      const trimmed = line.trim();
      if (!trimmed || trimmed.startsWith('#')) {
        output.push(line);
        continue;
      }
      const eq = trimmed.indexOf('=');
      const key = eq > 0 ? trimmed.slice(0, eq).trim() : '';
      if (key && setKeys.has(key)) {
        output.push(`${key}=${values[key]}`);
        seenKeys.add(key);
      } else {
        output.push(line);
      }
    }
    for (const k of setKeys) {
      if (!seenKeys.has(k)) output.push(`${k}=${values[k]}`);
    }
  } else {
    output.push('# Agent environment — Telegram bot credentials');
    output.push('# Generated by `ascendops bot create`');
    output.push('');
    for (const k of Object.keys(values)) output.push(`${k}=${values[k]}`);
  }

  // Ensure trailing newline exactly once.
  let content = output.join('\n');
  if (!content.endsWith('\n')) content += '\n';
  writeFileSync(envPath, content, 'utf-8');
  try { chmodSync(envPath, 0o600); } catch { /* ignore on Windows */ }
}

interface UpdateUser {
  chatId: number;
  fromId: number;
  username?: string;
  firstName?: string;
}

/**
 * Drain getUpdates and pick the most recent /start (or any message) from a
 * non-bot user. Returns null when no qualifying message is found.
 *
 * Telegram getUpdates returns nothing for chats the bot hasn't seen yet —
 * the user must /start the bot first.
 */
async function pickUserFromUpdates(api: TelegramAPI): Promise<UpdateUser | null> {
  let updates;
  try {
    updates = await api.getUpdates(0, 1);
  } catch (err) {
    console.error(`  getUpdates failed: ${err instanceof Error ? err.message : String(err)}`);
    return null;
  }

  const results: any[] = (updates && Array.isArray(updates.result)) ? updates.result : [];
  if (results.length === 0) return null;

  // Prefer the most recent /start, fall back to most recent message.
  const messages = results.map(u => u.message).filter(Boolean).reverse();
  const startMatch = messages.find(m => typeof m.text === 'string' && m.text.trim().startsWith('/start'));
  const chosen = startMatch ?? messages[0];
  if (!chosen || !chosen.chat) return null;
  const from = chosen.from ?? {};
  if (from.is_bot) return null;
  return {
    chatId: chosen.chat.id,
    fromId: from.id,
    username: from.username,
    firstName: from.first_name,
  };
}

interface CreateOptions {
  org?: string;
  instance: string;
  yes?: boolean;
}

async function botCreate(agentName: string, opts: CreateOptions): Promise<void> {
  if (!/^[a-z0-9_-]+$/.test(agentName)) {
    console.error(`Error: agent name "${agentName}" must match /^[a-z0-9_-]+$/`);
    process.exit(1);
  }

  const projectRoot = findProjectRoot();
  const resolved = resolveAgentDir(projectRoot, agentName, opts.org);
  if (!resolved) {
    console.error(`Error: agent "${agentName}" not found under any org in ${projectRoot}/orgs/`);
    console.error('Add it first with: ascendops add-agent ' + agentName + ' --org <org>');
    process.exit(1);
  }

  const { dir: agentDir, org } = resolved;
  const envPath = join(agentDir, '.env');
  const originalContent = existsSync(envPath) ? readFileSync(envPath, 'utf-8') : null;
  const existingEnv = parseExistingEnv(envPath);

  console.log('');
  console.log(`Provisioning Telegram bot for agent "${agentName}" in org "${org}".`);
  console.log(`Target file: ${envPath}`);
  console.log('');
  console.log('Step 1 — Create the bot at @BotFather (skip if you already have a token):');
  console.log('   1. Open Telegram and message @BotFather');
  console.log('   2. Send /newbot');
  console.log('   3. Choose a display name and a username ending in "_bot" or "Bot"');
  console.log('   4. Copy the BOT_TOKEN it gives you');
  console.log('');

  const iface = rl();
  try {
    const defaultToken = existingEnv.BOT_TOKEN || '';
    const tokenPrompt = defaultToken
      ? `Paste BOT_TOKEN (press Enter to keep existing): `
      : `Paste BOT_TOKEN: `;
    const tokenAnswer = await ask(iface, tokenPrompt);
    const botToken = tokenAnswer || defaultToken;

    if (!botToken) {
      console.error('  Error: BOT_TOKEN is required.');
      process.exit(1);
    }
    if (!/^\d+:[A-Za-z0-9_-]+$/.test(botToken)) {
      console.error('  Error: BOT_TOKEN does not look like a Telegram token (expected <digits>:<chars>).');
      console.error('  Check @BotFather and re-run this command.');
      process.exit(1);
    }

    console.log('');
    console.log('Step 2 — Verifying BOT_TOKEN with Telegram (getMe)...');

    const api = new TelegramAPI(botToken);
    let me: any;
    try {
      me = await api.getMe();
    } catch (err) {
      console.error(`  Telegram getMe failed: ${err instanceof Error ? err.message : String(err)}`);
      console.error('  This usually means: the token is wrong/revoked, or you have no internet right now.');
      console.error('  Fix the token at @BotFather (or check your connection), then re-run.');
      process.exit(1);
    }

    const botUsername: string = me?.result?.username ?? '';
    const botId: number = me?.result?.id;
    if (!botUsername || !botId) {
      console.error('  Telegram getMe returned an unexpected shape — cannot proceed.');
      console.error('  Raw response: ' + JSON.stringify(me).slice(0, 200));
      process.exit(1);
    }
    console.log(`  Verified: bot is @${botUsername} (id ${botId}).`);

    console.log('');
    console.log(`Step 3 — Open Telegram, search for @${botUsername}, and send /start.`);
    console.log('   This is what tells the bot who you are. Do it from the account that');
    console.log('   should be allowed to control this agent.');
    await ask(iface, '   Press Enter once you have sent /start...');

    console.log('');
    console.log('Step 4 — Reading the chat id back via getUpdates...');

    // Two attempts — sometimes the first call returns before Telegram has
    // queued the /start.
    let user = await pickUserFromUpdates(api);
    if (!user) {
      console.log('  No /start seen yet — waiting 3s and retrying once...');
      await new Promise(r => setTimeout(r, 3000));
      user = await pickUserFromUpdates(api);
    }

    if (!user) {
      console.error('  Could not find a /start message from a real user.');
      console.error('  Make sure you actually sent /start to @' + botUsername + ' from your own');
      console.error('  account (not from a channel, not from another bot). Then re-run this command.');
      process.exit(1);
    }

    const chatId = String(user.chatId);
    // The daemon's authorization gate accepts numeric Telegram user IDs only.
    // Keep the username for display, but never persist it as ALLOWED_USER.
    const allowedUser = String(user.fromId);
    const displayName = user.firstName || user.username || `id ${user.fromId}`;
    console.log(`  Captured: chat_id=${chatId} allowed_user=${allowedUser} (${displayName})`);

    if (!opts.yes) {
      const confirm = await ask(iface, `  Write to ${envPath}? [Y/n]: `);
      if (confirm && confirm.toLowerCase().startsWith('n')) {
        console.log('  Aborted — no file written.');
        process.exit(0);
      }
    }

    const merged: Record<string, string> = {
      BOT_TOKEN: botToken,
      CHAT_ID: chatId,
      ALLOWED_USER: allowedUser,
    };
    writeEnv(envPath, merged, originalContent);

    console.log('');
    console.log('Done. Wrote BOT_TOKEN + CHAT_ID + ALLOWED_USER to:');
    console.log(`  ${envPath}`);
    console.log('  (chmod 600 — owner read/write only)');
    console.log('');
    console.log('Next: ascendops start ' + agentName);
  } finally {
    iface.close();
  }
}

export const botCommand = new Command('bot')
  .description('Bot management — provision a Telegram bot for an agent');

botCommand
  .command('create')
  .argument('<agent_name>', 'Agent name (must already exist via add-agent)')
  .option('--org <org>', 'Organization name (auto-detected if only one)')
  .option('--instance <id>', 'Instance ID', 'default')
  .option('-y, --yes', 'Skip the final write confirmation prompt')
  .description('Provision a Telegram bot for <agent_name>: walk through @BotFather, verify token, capture chat_id, write .env')
  .action(botCreate);
